const { test, expect } = require('@playwright/test');
const api='https://api.github.com/repos/nowcika/git-scenario-solution';
const source='https://api.github.com/repos/nowcika/git-scenario-lab';
async function json(r,u){const x=await r.get(u);expect(x.ok(),`${u}: ${x.status()}`).toBeTruthy();return x.json()}
async function content(r,p,ref){const d=await json(r,`${api}/contents/${p}?ref=${encodeURIComponent(ref)}`);return Buffer.from(d.content.replace(/\s/g,''),'base64').toString('utf8')}
async function missing(r,p,ref){return (await r.get(`${api}/contents/${p}?ref=${encodeURIComponent(ref)}`)).status()===404}
async function commits(r,ref){return json(r,`${api}/commits?sha=${encodeURIComponent(ref)}&per_page=30`)}
test('배포 사이트와 18개 시나리오',async({request})=>{const x=await request.get('https://nowcika.github.io/git-lab-practice/');expect(x.ok()).toBeTruthy();expect(await x.text()).toContain('18개 평가 항목 · 290점');const s=await(await request.get('https://nowcika.github.io/git-lab-practice/scenarios.js')).text();expect(s).toContain('git-scenario-solution');expect((s.match(/\{ id:'/g)||[]).length).toBe(18)});
test('원본 문제 브랜치',async({request})=>{for(const n of ['upstream-update','conflict-left','conflict-right','revert','rebase-topic','rebase-base','reset','reflog-base','amend','cherry-source','diff-base','diff-target','show-source','patch-source','blame','branch-workflow','actions-release','pages'])expect((await request.get(`${source}/branches/${encodeURIComponent(`scenario/${n}`)}`)).ok(),n).toBeTruthy()});
test('remote conflict revert rebase',async({request})=>{expect(await content(request,'instructor-update.md','solution/upstream-sync')).toContain('UPSTREAM-SYNC-COMPLETE');const p=await content(request,'team-plan.md','solution/conflict');for(const x of ['프론트엔드: UI 배포 준비','백엔드: API 배포 준비','공동 확인: 통합 테스트 완료'])expect(p).toContain(x);expect((await commits(request,'solution/conflict')).some(c=>c.parents.length>=2)).toBeTruthy();expect(await content(request,'shared-config.json','solution/external-remote')).toContain('REMOTE-LIBRARY-V1');expect(await missing(request,'secrets.env','solution/revert')).toBeTruthy();expect((await commits(request,'solution/revert')).some(c=>c.commit.message.startsWith('Revert '))).toBeTruthy();expect(await content(request,'notes/base-update.txt','solution/rebase')).toBeTruthy();expect(await content(request,'notes/topic.txt','solution/rebase')).toBeTruthy();expect((await commits(request,'solution/rebase')).every(c=>c.parents.length<=1)).toBeTruthy()});
test('reset reflog amend cherry-pick',async({request})=>{expect(await content(request,'stable-config.txt','solution/reset')).toContain('STABLE-CONFIG-V1');expect(await missing(request,'unwanted-experiment.txt','solution/reset')).toBeTruthy();expect(await content(request,'recovered-note.txt','solution/reflog')).toContain('REFLOG-RECOVERED-COMMIT');const n=await content(request,'release-note.md','solution/amend');expect(n).toContain('# Release Note');expect(n).toContain('Version: draft');expect((await commits(request,'solution/amend'))[0].commit.message).toBe('docs: add release note');expect(await content(request,'urgent-fix.txt','solution/cherry-pick')).toContain('CHERRY-PICK-HOTFIX-2026')});
test('diff show patch blame',async({request})=>{const d=await content(request,'reports/change.patch','solution/diff');for(const x of ['diff --git','SERVICE_MODE=production','TIMEOUT=60','DIFF-TARGET-2026'])expect(d).toContain(x);const s=await content(request,'reports/show-report.md','solution/show');for(const x of ['fix: restore missing deployment configuration','SHOW-EVIDENCE-4821','forensic.txt'])expect(s).toContain(x);expect(await content(request,'patch-feature.txt','solution/patch')).toContain('FORMAT-PATCH-TRANSFER-2026');const b=await content(request,'reports/blame-answer.md','solution/blame');for(const x of ['BLAME-OWNER-7392','Release Manager','docs: add release approval check'])expect(b).toContain(x)});
test('브랜치 이동과 amend',async({request})=>{expect(await content(request,'frontend-task.txt','solution/branch-a')).toContain('BRANCH-A-ORIGINAL');expect(await missing(request,'backend-task.txt','solution/branch-a')).toBeTruthy();expect(await content(request,'frontend-task.txt','solution/branch-b')).toContain('MOVED-AND-AMENDED-2026');expect(await content(request,'backend-task.txt','solution/branch-b')).toContain('BRANCH-B-BACKEND');const h=await commits(request,'solution/branch-b');expect(h[0].commit.message).toBe('feat: move and refine shared task');expect(h.every(c=>c.parents.length<=1)).toBeTruthy()});
test('Actions Release와 asset',async({request})=>{const w=await content(request,'.github/workflows/release.yml','solution/actions-release');expect(w).toContain('contents: write');expect(w).toContain('gh release create');const r=await json(request,`${api}/releases/tags/release-v1.0.0`);expect(r.draft).toBeFalsy();expect(r.assets.some(a=>a.name==='scenario-artifact.txt'&&a.state==='uploaded')).toBeTruthy()});
test('Pages 실제 서비스',async({request})=>{expect(await content(request,'docs/index.html','solution/pages')).toContain('PAGES-LIVE-2026');const live=await request.get('https://nowcika.github.io/git-scenario-solution/');expect(live.ok()).toBeTruthy();expect(await live.text()).toContain('PAGES-LIVE-2026')});
test('완료 tag',async({request})=>expect((await request.get(`${api}/git/ref/tags/${encodeURIComponent('solution-v1.0.0')}`)).ok()).toBeTruthy());
